export const Icons: { [key: string]: any } = {
  chartjs: "/icons/chartjs-logo.svg",
  react: "/icons/react-2.svg",
  sass: "/icons/sass-1.svg",
  node: "/icons/nodejs-1.svg",
  bootstrap: "/icons/bootstrap-4.svg",
  mysql: "/icons/mysql-6.svg",
  html: "/icons/html5-2.svg",
  css: "/icons/css-3.svg",
  next: "/icons/nextjs-2.svg",
  git: "/icons/git-icon.svg",
  axios: "/icons/axios-vector-logo.png",
  reactnative: "/icons/react-1.svg",
  typescript: "/icons/typescript.svg",
  yarn: "/icons/yarn.svg",
  redux: "/icons/redux.svg",
  reduxsaga: "/icons/redux-saga.svg",
}
