export const Icons: { [key: string]: any } = {
  chartjs: "https://www.chartjs.org/img/chartjs-logo.svg",
  react: "https://cdn.worldvectorlogo.com/logos/react-2.svg",
  sass: "https://cdn.worldvectorlogo.com/logos/sass-1.svg",
  node: "https://cdn.worldvectorlogo.com/logos/nodejs-1.svg",
  bootstrap: "https://cdn.worldvectorlogo.com/logos/bootstrap-4.svg",
  mysql: "https://cdn.worldvectorlogo.com/logos/mysql-6.svg",
  html: "https://cdn.worldvectorlogo.com/logos/html5-2.svg",
  css: "https://cdn.worldvectorlogo.com/logos/css-3.svg",
  next: "https://cdn.worldvectorlogo.com/logos/nextjs-2.svg",
  git: "https://cdn.worldvectorlogo.com/logos/git-icon.svg",
  axios: "https://vectorlogoseek.com/wp-content/uploads/2019/04/axios-vector-logo.png",
  reactnative: "https://cdn.worldvectorlogo.com/logos/react-1.svg",
  npm: "https://cdn.worldvectorlogo.com/logos/npm.svg",
  typescript: "https://cdn.worldvectorlogo.com/logos/typescript.svg",
  yarn: "https://cdn.worldvectorlogo.com/logos/yarn.svg",
  redux: "https://cdn.worldvectorlogo.com/logos/redux.svg",
  reduxsaga: "https://cdn.worldvectorlogo.com/logos/redux-saga.svg",
}
